name: github pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [notes-commit-event]
jobs:
  pre:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Notes
        uses: actions/checkout@v4
        with:
          repository: Trouvaille0198/DigitalGarden0198
          token: ${{ secrets.NOTES-PAT }}
          sparse-checkout: Notes
          ref: main

      - name: Move Notes to docs
        run: mv Notes/* docs/
        shell: bash

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: pre

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
